# Generated by Django 3.2.6 on 2022-08-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecom_products',
            name='product_keyword',
        ),
        migrations.RemoveField(
            model_name='ecom_products',
            name='product_specification',
        ),
        migrations.RemoveField(
            model_name='ecom_products',
            name='product_viewcount',
        ),
        migrations.AddField(
            model_name='ecom_products',
            name='stock_limit',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
